#!/bin/sh

make maintainer-clean

rm -rf autom4te.cache
rm -f aclocal.m4
rm -f autoscan.log
rm -f config.rpath
rm -f configure
rm -f configre.scan
rm -f depcomp
rm -f gtk-doc.make
rm -f INSTALL
rm -f install-sh
rm -f missing
rm -f makepo
rm -f rebuild

cd po
rm -f Makefile.in
rm -f linnya.pot
rm -f *.gmo
rm -f *.po~

cd ../doc/reference
rm -f linnya*
