#!/bin/sh
# MusicMe uninstall file
# Please run as root

ROOT_UID=0
E_NOTROOT=67
DEFAULT_DIR=/home/yy/test
E_XCD=66
E_LOCATION=66

if [ "$UID" -ne "$ROOT_UID" ]
then
	echo "Must be root to run the script."
	exit $E_NOTROOT
fi

path=$(cd "$(dirname "$0")"; pwd)
INSTALL_DIR=${path%/share/linnya}

if [ "$path" = "$INSTALL_DIR" ]
then
	echo "The location of script is wrong, Please put it in \$linnyainstalldir/share/linnya and try again."
	exit $E_LOCATION
fi

cd $INSTALL_DIR
if [ "$PWD" != "$INSTALL_DIR" ]
then
	echo "Cannot enter directory $INSTALL_DIR"
	exit $E_XCD
fi

rm bin/linnya
rm -r share/linnya
rm share/applications/linya.desktop
rm share/icons/hicolor/64x64/apps/linnya.png
rm share/icons/hicolor/64x64/apps/linnya_trayicon.png
rm share/locale/*/LC_MESSAGES/linnya.mo

echo "Linnya has been sussessfully uninstalled"
exit 0
